<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>聊天室</title>

    <!-- Bootstrap -->
    <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/static/vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/build/css/custom.min.css" rel="stylesheet">
    <script  type="text/javascript" src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>

<body class="login">
    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form name="user_login" id="user_login" action="">
                    <h1>聊天室登录</h1>
                    <div>
                        <input type="text" class="form-control" name="user_name" placeholder="用户名" required="" />
                    </div>
                    <div>
                        <input type="password" class="form-control" name="password" placeholder="密码" required="" />
                    </div>
                    <div>
                        <a class="btn btn-default submit" id="login_submit" href="javascript:;">登录</a>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">
                        <p class="change_link"> 新用户?
                            <a href="/index/login/register" class="to_register"> 注册 </a>
                        </p>

                        <div class="clearfix"></div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</body>
</html>

<script>
    $("#login_submit").click(function () {
        var data = $("#user_login").serializeArray();
        $.post("/api/login/index",data,function (returnJson) {
            if(returnJson.status == false){
                alert(returnJson.msg);
                return false;
            }
            window.location.href = "/"
        });
    });
</script>
