<!-- 添加好友弹窗 start -->
<div class="modal fade" id="modal-add-friends">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">添加好友</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="box-body">
                        <div class="form-group">
                            <input name="friend_id" value="" type="hidden" id="add-friend-user_id">
                            <label  class="col-sm-2 control-label">分组：</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="add-friend-group_id">
                                    <?php foreach ($groups as $key=>$data):?>
                                        <option value="<?php echo $data['id'] ;?>"><?php echo $data['name'];?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                            <label  class="col-sm-2 control-label">理由：</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="add-friend-reason" placeholder="我是.."></textarea>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="add-friends-button">确定</button>
            </div>
        </div>
    </div>
</div>
<!-- 添加好友弹窗 end -->