<!-- 查询结果弹窗 start -->
<div class="modal fade" id="modal-search-friends-result">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">查询结果</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="box-body">
                        <div class="form-group" id="search-user-result">

                        </div>
                        <div class="form-group">
                            <label for="house_name" class="col-sm-2 control-label">总数：<span id="search-user-total">0</span>条</label>
                            <label for="house_name" style="display: none" class="col-sm-2 control-label">页码：<span id="search-user-page"></span></label>
                            <button type="button" style="display: none" class="btn btn-default pull-right" id="search-user-down" data-dismiss="modal">下一页</button>
                            <button type="button" style="display: none" class="btn btn-default pull-right" id="search-user-up" data-dismiss="modal">上一页</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>
<!-- 查询结果弹窗 end -->