<!-- 查询弹窗 start -->
<div class="modal fade" id="modal-search-friends">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">添加好友</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="search-friends-form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="house_name" class="col-sm-2 control-label">查询：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="user-search-str" placeholder="用户ID|用户账号|昵称">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="search-friends-button">查询</button>
            </div>
        </div>
    </div>
</div>
<!-- 查询弹窗 end -->